hypertrace/hypertrace

- README.md
- docker/README.md
- docker/docker-compose.yml
- healthcheck for UI is moved to image so removed that from docker-compose. (https://github.com/hypertrace/hypertrace-ui/pull/110)
- Added link to troubleshooting doc. 
- Added `docker-compose pull` as explicit step as per the discussion.
> Adds link to troubleshooting docs and removes healthcheck for UI. 

- docker/docker-compose.yml
verified in docker-compose
```
hypertrace-federated-service   java -cp /app/resources:/a ...   Up (healthy)   9001/tcp, 9002/tcp                                                                   
```
> reduces config for federated service

- docker/docker-compose.yml
QueryService is part of federated services that fetches data from pinot. QueryServices fetches brokers lists for pinot via zookeeper with data changed watcher. So, this will help us to start federated service parallel to pinot, but it will able to server traffic correctly when pinot will be healthy. But, to improve startup time, removing deps from pinot for federated service.
> Removes deps from pinot for federated service 

- docker/docker-compose.yml
note the succinct command for kafka-zookeeper
```bash
$ docker-compose ps
Name                          Command                  State                                               Ports                                        
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
all-views-creator              wait-for-it.sh -h pinot -p ...   Exit 0                                                                                              
all-views-generator            java -cp /app/resources:/a ...   Up (healthy)   8099/tcp                                                                             
attributes-bootstrapper        wait-for-it.sh -h hypertra ...   Exit 0 …
```
> Updates to new kafka-zookeeper image inlining healthcheck

- docker/docker-compose.yml
Randomly tidies mongo while at it
See https://github.com/hypertrace/schema-registry/pull/6
> Uses snazzy new schema-registry image to reduce download size and logs

- docker/docker-compose.yml
When this change is merged, by default we use the :main tag for 3rd
party services (except mongo which lacks a HT image)
Most notably, this uses the much faster Pinot build which depending
on laptop starts in less than 30s even when thrashed by all the other
processes:
```bash
$ docker logs pinot 2>&1|grep 'since launch'
07:17:50,407 INFO  [main] command.StartServiceManagerCommand (StartServiceManagerCommand.java:285) - Starting a Pinot [SERVICE_MANAGER] at 0.027s since launch
07:17:57,815 INFO  [main] command.StartServiceManagerCommand (StartServiceManagerCommand.java:287) - Started Pinot [SERVICE_MANAGER] instance [ServiceManager_d428313909fb_7098] at 7.436s since launch
07:17:57,874 INFO  [main] command.StartServiceManagerCommand (StartServiceManagerCommand.java:285) - Starting a Pinot …
```
> Finishes all 3rd party images, notably Pinot

- docker/docker-compose.yml
- docker/misc/docker-compose-tools.yml
This federated service PR - https://github.com/hypertrace/hypertrace-federated-service/pull/22 - merges config-bootstrapper into it as a background task.
> Merges config-bootstrapper as part of federated

- docker/docker-compose.yml
- docker/misc/docker-compose-tools.yml
we have moved all-views-creator which install schema as part of bootstrapping as pinot image itself. Ref PR - https://github.com/hypertrace/pinot/pull/28
So, this PR removes it and moves to misc for one-time use if needed.
> Removes the all-views-creator as startup jobs

- .circleci/config.yml
This PR enables nightly run of the CI to early catch breaking changes.
Ping @adriancole @JBAhire @kotharironak
> chore(ci): enables nightly CI for early catching breaking changes.

- .circleci/tests.sh
- docker/docker-compose.yml
- docker/misc/docker-compose-tools.yml
This simplifies the terminology we use by getting rid of the term "federated". It also makes image discovery easier by calling the top level docker image "hypertrace"
This is WIP as it requires a publish to fix the helm side accordingly
depends on https://github.com/hypertrace/hypertrace-service/pull/25
see https://github.com/hypertrace/hypertrace-service/issues/18
> renames hypertrace-federated-service to hypertrace

- docker/docker-compose.yml
As we have moved to use KafkaStream, latest span-normalizer images need pre-creation on topics.
- refere issue https://github.com/hypertrace/kafka-streams-framework/issues/5
So, we now need service_healthy deps on span-normalizer. Updating that as part of this PR.
> updates span-normalizer with additional conditions and pre-create topics

- .circleci/config.yml
- .circleci/tests.sh
- docker/docker-compose.yml
Since we don't have releases but use `main` all the time, it is good we avoid cache layers to make sure we always use last versions.
Ping @JBAhire @kotharironak
> chore(ci): disable docker_layer_caching to pull latest version always

- .circleci/config.yml
Follows from #58
Ping @adriancole
> chore(ci): uses docker pull instead of disabling the cache to reuse cached layers.

- docker/docker-compose.yml
Please don't undo this again as parallel start can cause docker to hang,
which is worse than waiting for services to become ready.
> Enforces strict ordering

- .circleci/config.yml
DLC is a paid feature that cost 200 credits/run and we are not yet getting a real improvement out of it, hence removing it.
Ping @aaron-steinfeld
> chore(ci): removes DLC from CI

- docker/docker-compose.yml
we moved the hypertrace-trace-enricher job from flink to kafkastream app which needs pre-creation of topics before starting app. So, in this PR,
- updating pre-creation flag
- reducing grouping window for local mode setup
> updates the pre-creation of topic flag for enricher job

- .circleci/config.yml
Reverts hypertrace/hypertrace#74
Since test isn't working properly we should revert this until we come up with a better one.
Ping @JBAhire
> Revert "chore(ci): adds support for windows."

- .github/ISSUE_TEMPLATE.md
This PR adds an issue template for opening an issue on this repo. Since we don't have that many issues yet I believe this template is good enough, once we get issues more varied and often we can jump into something more sophisticated like https://github.com/openzipkin/zipkin/issues/new/choose
> chore: adds issue template.

- kubernetes/data-services/Chart.yaml
- kubernetes/platform-services/Chart.yaml
This PR,
- updates helm charts for all the services (except `raw-spans-grouper` and `hypertrace-service` ) to latest.
> updates helm charts

- docker/docker-compose-zipkin-example.yml
The new sample app is much more efficient and also smaller.
This should help reduce overall bootstrap load when running examples.
Here's a comparison before after during http requests in a for loop. Unscientific on load, but memory is definitely less.
before
```
openzipkin/example-sleuth-webmvc     latest              4b4354aa7433        7 days ago          428MB
CONTAINER ID        NAME                   CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
e8d2d9b71ea1        hypertrace-ingester    29.63%              377.7MiB / 1.944GiB   18.97%              646kB / 640kB       195MB / 156kB       48
427672a37f5c        hypertrace             71.20%              188.8MiB / 1.944GiB   9.48%               716kB / 649kB       212MB / …
```
> Moves to a smaller and more efficient zipkin example app

- docker/docker-compose-zipkin-example.yml
The Zipkin example moved to GitHub Container Repository to prevent build
outages from the impending 1 Nov 100-200 pull limit/6hrs on Docker Hub's
registry.
> Reduces Docker Hub usage by pulling examples from GitHub Container Registry

- .circleci/tests.sh
Removes link checks from here as we have already added them in `hypertrace-service` CI in this PR: https://github.com/hypertrace/hypertrace-service/pull/44
> removes link checks from CI 

- docker/docker-compose.yml
This exposes attribute service to the ingester image, which will use attributes to support https://github.com/hypertrace/hypertrace-ingester/pull/49
Locally tested by building the linked ingester and spinning up a local HT cluster, verifying the new attribute-dependent functionality.
- [n/a] I have added tests that prove my fix is effective or that my feature works
> chore: expose attribute service config to ingest

- docker/docker-compose-zipkin-example.yml
This updates the zipkin example and also makes it easier for people to control what's running.
For example, they can set `BRAVE_EXAMPLE=webmvc25-jetty` to run a Java 1.6 instrumented app.
```bash
BRAVE_EXAMPLE=webmvc25-jetty docker-compose -f docker-compose.yml -f docker-compose-zipkin-example.yml up
```
N/A
N/A
> Updates zipkin example

- README.md
Removes reference to archived repos and links hypertrace-ingester repo as we merged ingestion pipeline into single repository with https://github.com/hypertrace/hypertrace-ingester/pull/15
> removes reference to archived repos and links hypertrace-ingester repo

- docker/docker-compose.yml
Based on my note here on the PR -  https://github.com/hypertrace/hypertrace-service/pull/51, we are using pinot-server health check in hypetrace service. Refer - https://github.com/hypertrace/hypertrace-service/pull/51#issuecomment-744181330
> Updating alias for pinot's all-in-one deployment

- .github/workflows/release-bot.yml
- kubernetes/data-services/Chart.yaml
- kubernetes/platform-services/Chart.yaml
This PR,
- updates helm charts
- adds release notification slack bot which will send updates on release channel in Hypertrace community slack. 
Deployed and tested helm charts locally. 
Slack notification will look like below:
> updates helm chart and adds release notification slack bot

- .github/workflows/create-charts.sh
- .github/workflows/header.txt
- .github/workflows/pull-release.yml
This PR, 
- adds workflow which pulls latest tags for all services and updates helm charts using script. 
- once charts are updates, it will automatically raise the PR. 
- This workflow runs on every Friday 6 AM UT/ 11:30 AM IST/ 10 PM PST (Thursday)
- https://github.com/peter-evans/create-pull-request
- https://github.com/marketplace/actions/find-latest-tag
> adds workflow to automate helm chart updates

- kubernetes/clusters/dev/values.yaml
The `raw-spans-grouper` - one of the components of the ingestion pipeline was not coming up in the `helm` setup with the `dev` profile.
We were getting the below exception:
```
2021-01-19 06:53:35.475 [raw-spans-to-structured-traces-grouping-job-42d66b5b-1f55-4ff5-b31d-415a68329068-StreamThread-4] ERROR o.h.c.r.RawSpansGrouper - Thread=[raw-spans-to-structured-traces-grouping-job-42d66b5b-1f55-4ff5-b31d-415a68329068-StreamThread-4] encountered=[org.apache.kafka.streams.errors.StreamsException: Could not create topic raw-spans-to-structured-traces-grouping-job-trace-emit-trigger-store-changelog.
at org.apache.kafka.streams.processor.internals.InternalTopicManager.makeReady(InternalTopicManager.java:148)
at org.apache.kafka.streams.processor.internals.StreamsPartitionAssignor.prepareChangelo …
```
> fixing streaming config due to name changes in latest charts

- .github/workflows/create-charts.sh
- .github/workflows/pull-release.yml
- README.md
- docker/docker-compose.yml
- kubernetes/clusters/standard/values.yaml
- kubernetes/platform-services/Chart.yaml
- kubernetes/platform-services/values.yaml
This change adds config service to both docker-compose and k8s deployments, as described in https://github.com/hypertrace/hypertrace-service/pull/60#issuecomment-763726172
Verified both deployment variants locally, making sure to read + write to config service.
> chore: add config service and update releases

- kubernetes/clusters/dev/values.yaml
There was an issue with helm values for hypertrace-view-generator. as per the helm chart [here](https://github.com/hypertrace/hypertrace-ingester/blob/d12c5b94d709f72e7ca66c269c08968320223569/hypertrace-view-generator/helm/values.yaml) `replicaCount` should be under generator but it was placed under resources. This was causing install failure. 
This PR resolves that. 
tested with EKS setup
> fix: helm values for hypertrace-view-generator

- .github/workflows/create-charts.sh
- .github/workflows/pull-release.yml
- kubernetes/platform-services/Chart.yaml
- kubernetes/platform-services/postgres/values.yaml
- kubernetes/platform-services/values.yaml
Tested automated pr creation. This pr https://github.com/rish691/hypertrace-1/pull/2 got created.
Currently not adding hypertrace-data-query & hypertrace-data-config service to release notes & compatibility matrix. 
Verified by running e2e test locally [with query services merged]
> feat: add macro services for query layer

- .github/ui-e2e-tests/package.json
- removes reference to non-hypertrace nomenclature. 
- disables gecko by default as it's causing chromedriver install failure sometimes. 
Thanks to @skjindal93 for pointing out gecko thing. 
tested this locally
> chore: cleanup package.json for ui e2e tests

- kubernetes/clusters/standard/values.yaml
- kubernetes/platform-services/values.yaml
Enable running hypertrace-data-config-service & hypertrace-data-query-service
Discussion on performance: https://github.com/hypertrace/hypertrace/discussions/194
> feat: enable running query services in `merged` mode

- README.md
- kubernetes/README.md
- kubernetes/config/hypertrace.properties
- kubernetes/data-services/templates/storage-aws.yml
- kubernetes/hypertrace.sh
- kubernetes/pre_post_install_task_generator.py
- updated regex for manifest creation to pick changes from modifications due to merged services. 
- updated README to explain how to install with kubernetes manifests
- tested commands locally
> fix: updated manifest creation regex to work with merged services and updated docs

- kubernetes/hypertrace.sh
- kubernetes/pre_post_install_task_generator.py
We were separating pre and post install hook manifests using regular expressions to extract config bootstrapper configs. This PR will change that hard coded service based manifest creation to hook based manifest creation. 
tested locally.
> fix: replaces RE with yaml parsing for hook based manifest creation

- docker/docker-compose.yml
- docker/postgres/docker-compose.yml
- Removed default container-name from docker-compose file to avoid conflicts by container name with deployments like this:
- Tested locally and also runs in e2e test. 
cc: @jcchavezs
> refactor: removed container name from docker-compose to avoid conflict

- docker/README.md
- docker/docker-compose.prometheus.yml
- docker/docker-compose.yml
- docker/prom.yml
As part of this ticket - https://github.com/hypertrace/hypertrace/issues/327 - on the context of providing application metrics support, this PR,
- adds the new docker-compose file for metrics pipeline
- corresponding hypertrace-ingester PR - https://github.com/hypertrace/hypertrace-ingester/pull/292
> feat: add docker-compose file for enable metrics pipeline
