hypertrace/hypertrace

- README.md
Very minor tweaks to the readme.
> docs: small tweaks to readme.

- kubernetes/data-services/Chart.yaml
- kubernetes/platform-services/Chart.yaml
This PR:
- Updates data services and platform services helm charts to latest available versions.
> updates helm charts for platform and data services

- docker/docker-compose.yml
note: depends on this PR - https://github.com/hypertrace/hypertrace-federated-service/pull/16
> merges hypertrace-ui into federated service

- docker/docker-compose.yml
This reverts commit 87179b027bcf8a907ea06ad127d8f5289789e5fa.
> Revert "merges hypertrace-ui into federated service (#21)"

- docker/docker-compose.yml
…23)"
This reverts commit ed58fae4cc2fa98868d5fe315d58ba685155ae8c.
> Merges Hypertrace UI into federated service

- kubernetes/data-services/Chart.yaml
- kubernetes/platform-services/Chart.yaml
- updates helm charts for all services except federated service.
> updates helm charts for platform & data services in helm setup

- .circleci/config.yml
- docker/docker-compose.yml
We have updated raw-spans-grouper job from flink to kafka stream - https://github.com/hypertrace/hypertrace-ingester/issues/2. The new kafka stream based app needs pre-created topics, updating required flag for the same.
> updates raw-spans-grouper changes

- .circleci/config.yml
- .circleci/inspect.sh
- .circleci/tests.sh
This PR makes it possible to display health status for every container, along with the logs, on failure.
Ping @adriancole
> chore(ci): adds healthy status on failure.

- docker/docker-compose.yml
- Ref PR - https://github.com/hypertrace/hypertrace/commit/05fe56bc1ada0b2bfc2edd662795959502e83e44
> fixed removed dependency in previous commit related to using hypetrace-ingester

- .circleci/config.yml
> chore(ci): adds support for windows.

- docker/docker-compose.yml
Solve the issue - https://github.com/hypertrace/pinot/issues/39
Associated PRs:
- https://github.com/hypertrace/kafka-streams-framework/pull/17
- https://github.com/hypertrace/pinot/pull/42
- https://github.com/hypertrace/view-generator-framework/pull/16
- https://github.com/hypertrace/hypertrace-ingester/pull/9
> removes dependency of schema-registry

- README.md
I just cleaned up some wording. There should be no conficts
> cleaned up some wording

- README.md
This PR,
- adds minimum resource requirements to run docker-compose in README
> adds resource requirements in README

- README.md
Adds minimum docker-engine and docker-compose version requirements in README.
> Adds requirements section

- .github/CONTRIBUTING.md
This PR,
- adds contributing guidelines in `.github` folder.
> adds contributing guidelines

- kubernetes/hypertrace.sh
This PR,
- Fixes #101 
- Adds `--clean` flag for installation in case issue like #101 occurs. 
- `--clean` will uninstall previously installed `data-services` as well as `platform-services` deployments if there are any before starting actual installation process.
> Fixes helm install failure issue in case of partial installation. 

- docker/docker-compose.yml
help in suppressing warning - https://github.com/hypertrace/pinot/issues/26
> overriding logging level to error for pinot service

- README.md
There was some confusion around production deployment of Hypertrace. 
This PR, 
- adds details and note around k8s for prod and staging.
- chore: adds e2e test badge
> adds k8s for production note and e2e test badge

- kubernetes/data-services/Chart.yaml
- kubernetes/platform-services/Chart.yaml
This PR, 
- Updates helm charts as per the latest releases of all services. 
I have deployed Hypertrace using this versions locally and everything is working fine.
> updates helm charts

- .github/code_of_conduct.md
- kubernetes/platform-services/Chart.yaml
> Adds code of conduct

- .github/workflows/release-bot.yml
adds bot name and logo using env variables
> updates slack release notification bot

- kubernetes/data-services/Chart.yaml
- kubernetes/platform-services/Chart.yaml
This PR,
- Updates helm charts as per the latest releases of all services. 
- **Note: This is auto-generated PR so please test and verify before merging.**
> [chore] updates helm charts

- kubernetes/data-services/Chart.yaml
- kubernetes/platform-services/Chart.yaml
- kubernetes/tmp/compatibility_matrix.txt
- release_notes.md
This PR,
- Updates helm charts as per the latest releases of all services. 
- **Note: This is auto-generated PR so please test and verify before merging.**
> chore: updates helm charts

- kubernetes/monitoring/README.md
- kubernetes/monitoring/dashboards/001-ingestion-pipeline-metrics.json
- kubernetes/monitoring/dashboards/002-query-layer-metrics.json
- As part of this PR (https://github.com/hypertrace/gateway-service/pull/78), have refactored few metrics. This PR makes corresponding changes in ReadMe and dashboard.
- Also updated readme and dashboard with newly added ingestion layer metrics
Verified locally, see the below screen shots
Done
> Updated dashboards and readme with new metrics

- kubernetes/README.md
Please include a summary of the change, motivation and context.
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally. 
Make sure that you have documented corresponding changes in this repository or [hypertrace docs repo](https://github.com/hypertrace/hypertrace-docs-website) if required.
> docs: fix a typo

- .github/graphql-e2e-tests/ingest-traces.sh
- .github/workflows/pull-release.yml
- .github/workflows/scripts/create-charts.sh
- docker/configs/hypertrace-collector/config.yml
- docker/docker-compose.yml
- docker/postgres/docker-compose.yml
- kubernetes/clusters/dev/values.yaml
- kubernetes/clusters/standard/values.yaml
- kubernetes/platform-services/Chart.yaml
- kubernetes/platform-services/values.yaml
- Fixes https://github.com/hypertrace/hypertrace/issues/179
- Our OpenTelemetry based [Hypertrace collector](https://github.com/hypertrace/hypertrace-collector) is ready to use now so replacing old opencensus based collector with it for both docker-compose and helm setup.
I tested docker-compose locally and helm setup with EKS and seems working well. 
```
NAME                             TYPE           CLUSTER-IP       EXTERNAL-IP                                                              PORT(S)                                                                                         AGE
bootstrap                        ClusterIP      10.100.72.240    <none>                                                                   9092/TCP …
```
> feat: swaps opencensus collector with otel based hypertrace-collector

- README.md
Updated README to 
- Add more details around use-cases
- Add details about community calls and GH discussions. 
- Removed unnecessary content
NA
NA
> docs: updated readme to add more focused content

- kubernetes/platform-services/Chart.yaml
- kubernetes/platform-services/values.yaml
> feat: Add adding alerting to k8s

- docker/configs/alert-rules.json
- docker/configs/notification-rules.json
- docker/docker-compose.alerting.yml
Update the env var for notification-channels path to `NOTIFICATION_CHANNELS_PATH`
> fix: Fix env var name for alerting service

- README.md
> chore: updating message of handling log4j issue

- README.md
- Cut the latest release for entity service of fix of log4j
> chore: updated the message for log4j fix
